lib/kuro_cams_web/router.ex
defmodule KuroCamsWeb.Router do
  use KuroCamsWeb, :router

  import KuroCamsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KuroCamsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KuroCamsWeb do
    pipe_through :browser

    get "/", HomeController, :index
  end

  ## Chats Routes

  scope "/", KuroCamsWeb do
    pipe_through [:browser, :require_authenticated_user]

    post "/chats", ChatController, :create
  end

  scope "/", KuroCamsWeb do
    pipe_through [:browser, :require_authenticated_user, :require_chat_authorized_user]

    get "/chats/:uuid", ChatController, :show
    delete "/chats/:uuid", ChatController, :delete
    post "/chats/:uuid/video_room", ChatController, :create_video_room
  end

  # Video Room Routes

  scope "/", KuroCamsWeb do
    pipe_through [:browser, :require_authenticated_user, :require_video_room_authorized_user]

    live "/video_rooms/:uuid", VideoRoomLive.Show, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", KuroCamsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: KuroCamsWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", KuroCamsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
  end

  scope "/", KuroCamsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
  end

  scope "/", KuroCamsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
  end
end

lib/kuro_cams_web/views/layout_view.ex
defmodule KuroCamsWeb.LayoutView do
  use KuroCamsWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])

    if path == current_path do
      "text-gray-800 dark:text-gray-100"
    else
      nil
    end
  end
end

lib/kuro_cams_web/templates/layout/app.html.heex
<%= @inner_content %>

lib/kuro_cams_web/templates/layout/cta.html.heex
<!-- CTA -->
<a
  class="flex items-center justify-between p-4 mb-8 text-sm font-semibold text-purple-100 bg-purple-600 rounded-lg shadow-md focus:outline-none focus:shadow-outline-purple"
  href="https://github.com/kuro-vale/kuro-cams"
  target="_blank"
>
  <div class="flex items-center">
    <svg
      class="w-5 h-5 mr-2"
      fill="currentColor"
      viewBox="0 0 20 20"
    >
      <path
        d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"
      ></path>
    </svg>
    <span>Star this project on GitHub</span>
  </div>
  <span>View more &RightArrow;</span>
</a>

lib/kuro_cams_web/templates/layout/desktop_sidebar.html.heex
<!-- Desktop sidebar -->
<aside
class="z-20 hidden w-64 overflow-y-auto bg-white dark:bg-gray-800 md:block flex-shrink-0"
>
    <div class="py-4 text-gray-500 dark:text-gray-400">
        <a
        class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200"
        href="#"
        >
        Kuro-Cams
        </a>
        <ul class="mt-6">
        <li class="relative px-6 py-3">
            <!-- Active items have the snippet below -->
            <!-- <span
            class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
            aria-hidden="true"
            ></span> -->

            <!-- Add this classes to an active anchor (a tag) -->
            <!-- text-gray-800 dark:text-gray-100 -->
            <%= if active_class(@conn, Routes.home_path(@conn, :index)) do %>
            <span
            class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
            aria-hidden="true"
            ></span>
            <% end %>
            <%= link raw(
            """
                <svg
                class="w-5 h-5"
                aria-hidden="true"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                ></path>
            </svg>
            <span class="ml-4">Home</span>
            """
            ), to: Routes.home_path(@conn, :index),
            class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.home_path(@conn, :index))}"
             %>
        </li>
        </ul>
        <ul>
        <%= if @current_user do %>
            <li class="relative px-6 py-3">
                <button
                class="inline-flex items-center justify-between w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                @click="togglePagesMenu"
                aria-haspopup="true"
                >
                <span class="inline-flex items-center">
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    >
                    <path
                        d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
                    ></path>
                    </svg>
                    <span class="ml-4">Chats</span>
                </span>
                <svg
                    class="w-4 h-4"
                    aria-hidden="true"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                >
                    <path
                    fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                    ></path>
                </svg>
                </button>
                <template x-if="isPagesMenuOpen">
                <ul
                    x-transition:enter="transition-all ease-in-out duration-300"
                    x-transition:enter-start="opacity-25 max-h-0"
                    x-transition:enter-end="opacity-100 max-h-xl"
                    x-transition:leave="transition-all ease-in-out duration-300"
                    x-transition:leave-start="opacity-100 max-h-xl"
                    x-transition:leave-end="opacity-0 max-h-0"
                    class="p-2 mt-2 space-y-2 overflow-hidden text-sm font-medium text-gray-500 rounded-md shadow-inner bg-gray-50 dark:text-gray-400 dark:bg-gray-900"
                    aria-label="submenu"
                >
                <%= if Enum.empty? @current_user.rooms do %>
                    <li
                    class="flex justify-between px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                    >
                    <p class="w-full">You don't have chats</p>
                    </li>
                <% end %>
                <%= for room <- @current_user.rooms do %>
                    <li
                    class="flex justify-between px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                    >
                    <%= link KuroCams.Accounts.get_user!(room.to_user).username, 
                    to: Routes.chat_path(@conn, :show, room.uuid), 
                    class: "w-full #{active_class(@conn, Routes.chat_path(@conn, :show, room.uuid))}" 
                    %>
                    <%= link raw(
                        """
                        <svg
                            class="w-4 h-4"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            role="img"
                            aria-hidden="true"
                        >
                            <path
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                            fill-rule="evenodd"
                            ></path>
                        </svg>
                        """
                    ),
                    to: Routes.chat_path(@conn, :delete, room.uuid), 
                    method: :delete 
                    %>
                    </li>
                <% end %>
                </ul>
                </template>
            </li>
        <% else %>
            <li class="relative px-6 py-3">
                <%= if active_class(@conn, Routes.user_registration_path(@conn, :new)) do %>
                <span
                class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
                aria-hidden="true"
                ></span>
                <% end %>
                <%= link raw(
                """
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                <path d="m11 11h-7.25c-.414 0-.75.336-.75.75s.336.75.75.75h7.25v7.25c0 .414.336.75.75.75s.75-.336.75-.75v-7.25h7.25c.414 0 .75-.336.75-.75s-.336-.75-.75-.75h-7.25v-7.25c0-.414-.336-.75-.75-.75s-.75.336-.75.75z"
                />
                </svg>
                <span class="ml-4">Register</span>
                """
                ), to: Routes.user_registration_path(@conn, :new),
                class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.user_registration_path(@conn, :new))}"
                %>
            </li>
            <li class="relative px-6 py-3">
                <%= if active_class(@conn, Routes.user_session_path(@conn, :new)) do %>
                <span
                class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
                aria-hidden="true"
                ></span>
                <% end %>
                <%= link raw(
                """
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                <path d="M12.804 9c1.038-1.793 2.977-3 5.196-3 3.311 0 6 2.689 6 6s-2.689 6-6 6c-2.219 0-4.158-1.207-5.196-3h-3.804l-1.506-1.503-1.494 1.503-1.48-1.503-1.52 1.503-3-3.032 2.53-2.968h10.274zm7.696 1.5c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5z"
                />
                </svg>
                <span class="ml-4">Login</span>
                """
                ), to: Routes.user_session_path(@conn, :new),
                class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.user_session_path(@conn, :new))}"
                %>
            </li>
        <% end %>
        </ul>
    </div>
</aside>

lib/kuro_cams_web/templates/layout/error_layout.html.heex
<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= live_title_tag assigns[:page_title] || "KuroCams", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
      rel="stylesheet"/>
  </head>
  <body>
    <div
        class="flex h-screen bg-gray-50 dark:bg-gray-900"
      >
      <div class="flex flex-col flex-1">
        <main class="h-full pb-16 overflow-y-auto">
          <div class="mt-12 container flex flex-col items-center px-6 mx-auto">
            <svg
              class="w-12 h-12 mt-8 text-purple-200"
              fill="currentColor"
              viewBox="0 0 20 20"
            >
              <path
                fill-rule="evenodd"
                d="M13.477 14.89A6 6 0 015.11 6.524l8.367 8.368zm1.414-1.414L6.524 5.11a6 6 0 018.367 8.367zM18 10a8 8 0 11-16 0 8 8 0 0116 0z"
                clip-rule="evenodd"
              ></path>
            </svg>
            <%= @inner_content %>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

lib/kuro_cams_web/templates/layout/live.html.heex
<%= @inner_content %>

lib/kuro_cams_web/templates/layout/mobile_sidebar.html.heex
<!-- Mobile sidebar -->
<!-- Backdrop -->
<div
x-show="isSideMenuOpen"
x-transition:enter="transition ease-in-out duration-150"
x-transition:enter-start="opacity-0"
x-transition:enter-end="opacity-100"
x-transition:leave="transition ease-in-out duration-150"
x-transition:leave-start="opacity-100"
x-transition:leave-end="opacity-0"
class="fixed inset-0 z-10 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center"
></div>
<aside
class="fixed inset-y-0 z-20 flex-shrink-0 w-64 mt-16 overflow-y-auto bg-white dark:bg-gray-800 md:hidden"
x-show="isSideMenuOpen"
x-transition:enter="transition ease-in-out duration-150"
x-transition:enter-start="opacity-0 transform -translate-x-20"
x-transition:enter-end="opacity-100"
x-transition:leave="transition ease-in-out duration-150"
x-transition:leave-start="opacity-100"
x-transition:leave-end="opacity-0 transform -translate-x-20"
@click.away="closeSideMenu"
@keydown.escape="closeSideMenu"
>
    <div class="py-4 text-gray-500 dark:text-gray-400">
        <a
        class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200"
        href="#"
        >
        Kuro-Cams
        </a>
        <ul class="mt-6">
        <li class="relative px-6 py-3">
            <!-- Active items have the snippet below -->
            <!-- <span
            class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
            aria-hidden="true"
            ></span> -->

            <!-- Add this classes to an active anchor (a tag) -->
            <!-- text-gray-800 dark:text-gray-100 -->
            <%= if active_class(@conn, Routes.home_path(@conn, :index)) do %>
            <span
            class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
            aria-hidden="true"
            ></span>
            <% end %>
            <%= link raw(
            """
                <svg
                class="w-5 h-5"
                aria-hidden="true"
                fill="none"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                viewBox="0 0 24 24"
                stroke="currentColor"
            >
                <path
                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
                ></path>
            </svg>
            <span class="ml-4">Home</span>
            """
            ), to: Routes.home_path(@conn, :index),
            class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.home_path(@conn, :index))}"
             %>
        </li>
        </ul>
        <ul>
        <%= if @current_user do %>
            <li class="relative px-6 py-3">
                <button
                class="inline-flex items-center justify-between w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                @click="togglePagesMenu"
                aria-haspopup="true"
                >
                <span class="inline-flex items-center">
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    >
                    <path
                        d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
                    ></path>
                    </svg>
                    <span class="ml-4">Chats</span>
                </span>
                <svg
                    class="w-4 h-4"
                    aria-hidden="true"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                >
                    <path
                    fill-rule="evenodd"
                    d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                    clip-rule="evenodd"
                    ></path>
                </svg>
                </button>
                <template x-if="isPagesMenuOpen">
                <ul
                    x-transition:enter="transition-all ease-in-out duration-300"
                    x-transition:enter-start="opacity-25 max-h-0"
                    x-transition:enter-end="opacity-100 max-h-xl"
                    x-transition:leave="transition-all ease-in-out duration-300"
                    x-transition:leave-start="opacity-100 max-h-xl"
                    x-transition:leave-end="opacity-0 max-h-0"
                    class="p-2 mt-2 space-y-2 overflow-hidden text-sm font-medium text-gray-500 rounded-md shadow-inner bg-gray-50 dark:text-gray-400 dark:bg-gray-900"
                    aria-label="submenu"
                >
                <%= if Enum.empty? @current_user.rooms do %>
                    <li
                    class="flex justify-between px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                    >
                    <p class="w-full">You don't have chats</p>
                    </li>
                <% end %>
                <%= for room <- @current_user.rooms do %>
                    <li
                    class="flex justify-between px-2 py-1 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200"
                    >
                    <%= link KuroCams.Accounts.get_user!(room.to_user).username, 
                        to: Routes.chat_path(@conn, :show, room.uuid), 
                        class: "w-full #{active_class(@conn, Routes.chat_path(@conn, :show, room.uuid))}" 
                    %>
                    <%= link raw(
                        """
                        <svg
                            class="w-4 h-4"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            role="img"
                            aria-hidden="true"
                        >
                            <path
                            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                            clip-rule="evenodd"
                            fill-rule="evenodd"
                            ></path>
                        </svg>
                        """
                    ),
                    to: Routes.chat_path(@conn, :delete, room.uuid), 
                    method: :delete 
                    %>
                    </li>
                <% end %>
                </ul>
                </template>
            </li>
        <% else %>
            <li class="relative px-6 py-3">
                <%= if active_class(@conn, Routes.user_registration_path(@conn, :new)) do %>
                <span
                class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
                aria-hidden="true"
                ></span>
                <% end %>
                <%= link raw(
                """
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                <path d="m11 11h-7.25c-.414 0-.75.336-.75.75s.336.75.75.75h7.25v7.25c0 .414.336.75.75.75s.75-.336.75-.75v-7.25h7.25c.414 0 .75-.336.75-.75s-.336-.75-.75-.75h-7.25v-7.25c0-.414-.336-.75-.75-.75s-.75.336-.75.75z"
                />
                </svg>
                <span class="ml-4">Register</span>
                """
                ), to: Routes.user_registration_path(@conn, :new),
                class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.user_registration_path(@conn, :new))}"
                %>
            </li>
            <li class="relative px-6 py-3">
                <%= if active_class(@conn, Routes.user_session_path(@conn, :new)) do %>
                <span
                class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg"
                aria-hidden="true"
                ></span>
                <% end %>
                <%= link raw(
                """
                    <svg
                    class="w-5 h-5"
                    aria-hidden="true"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                <path d="M12.804 9c1.038-1.793 2.977-3 5.196-3 3.311 0 6 2.689 6 6s-2.689 6-6 6c-2.219 0-4.158-1.207-5.196-3h-3.804l-1.506-1.503-1.494 1.503-1.48-1.503-1.52 1.503-3-3.032 2.53-2.968h10.274zm7.696 1.5c.828 0 1.5.672 1.5 1.5s-.672 1.5-1.5 1.5-1.5-.672-1.5-1.5.672-1.5 1.5-1.5z"
                />
                </svg>
                <span class="ml-4">Login</span>
                """
                ), to: Routes.user_session_path(@conn, :new),
                class: "inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 #{active_class(@conn, Routes.user_session_path(@conn, :new))}"
                %>
            </li>
        <% end %>
        </ul>
    </div>
</aside>

lib/kuro_cams_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "KuroCams", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
      rel="stylesheet"/>
    <script>window.userToken = "<%= assigns[:user_token] %>";</script>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"
      defer></script>
    <script>
    function data() {
      return {
        dark: true,
        isSideMenuOpen: false,
        toggleSideMenu() {
          this.isSideMenuOpen = !this.isSideMenuOpen
        },
        closeSideMenu() {
          this.isSideMenuOpen = false
        },
        isNotificationsMenuOpen: false,
        toggleNotificationsMenu() {
          this.isNotificationsMenuOpen = !this.isNotificationsMenuOpen
        },
        closeNotificationsMenu() {
          this.isNotificationsMenuOpen = false
        },
        isProfileMenuOpen: false,
        toggleProfileMenu() {
          this.isProfileMenuOpen = !this.isProfileMenuOpen
        },
        closeProfileMenu() {
          this.isProfileMenuOpen = false
        },
        isPagesMenuOpen: true,
        togglePagesMenu() {
          this.isPagesMenuOpen = !this.isPagesMenuOpen
        },
        // Modal
        isModalOpen: false,
        openModal() {
          this.isModalOpen = true
        },
        closeModal() {
          this.isModalOpen = false
        },
      }
    }
    </script>
  </head>
  <body>
    <div
        class="flex h-screen bg-gray-50 dark:bg-gray-900"
        :class="{ 'overflow-hidden': isSideMenuOpen}"
      >
      <%= render("desktop_sidebar.html", assigns) %>
      <%= render("mobile_sidebar.html", assigns) %>
      <div class="flex flex-col flex-1">
        <%= render("topbar.html", assigns) %>
        <main class="h-full pb-16 overflow-y-auto">
          <%= @inner_content %>
        </main>
      </div>
    </div>
  </body>
</html>